matrix:
  include:
    - os: linux
      services: docker
      sudo: required
      install: docker build . -t jshrake/grimoire:18.04 -f Dockerfile.1804
      language: generic
    - os: osx
      language: rust
      cache: cargo
      rust: stable
      install: brew install sdl2 gstreamer gst-plugins-base;
      script:
        - rustc --version
        - cargo --version
        - cargo test --all --verbose
        - cargo doc --verbose
    - os: osx
      language: rust
      cache: cargo
      rust: beta
      install: brew install sdl2 gstreamer gst-plugins-base;
      script:
        - rustc --version
        - cargo --version
        - cargo test --all --verbose
        - cargo doc --verbose
    - os: osx
      language: rust
      cache: cargo
      rust: nightly
      allow_failures: true
      install: brew install sdl2 gstreamer gst-plugins-base;
      script:
        - rustc --version
        - cargo --version
        - cargo test --all --verbose
        - cargo doc --verbose
branches:
  only:
    - master