[package]
name = "grimoire"
description = "grimoire is a cross-platform live-coding tool for creating GLSL shader demos"
version = "0.2.1"
authors = ["Justin Shrake <justinshrake@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/jshrake/grimoire"
keywords = ["shadertoy", "glsl", "shaders", "creative", "graphics"]
readme = "README.md"
include = ["src/*.rs","src/*.glsl","Cargo.toml","README.md","SPEC.md","FAQ.md","LICENSE-APACHE","LICENSE-MIT"]
edition = "2018"

[badges]
travis-ci = { repository = "jshrake/grimoire" }
maintenance = { status = "experimental" }

[dependencies]
byte-slice-cast     = "0.3"
chrono              = "0.4"
clap                = "2.32"
env_logger          = "0.7"
failure             = "0.1"
gleam               = "0.8"
glsl-include        = "0.3"
gstreamer           = "0.15"
gstreamer-app       = "0.15"
gstreamer-audio     = "0.15"
gstreamer-video     = "0.15"
image               = "0.22"
lazy_static         = "1.4"
log                 = "0.4"
notify              = "4.0"
regex               = "1"
sdl2                = "0.32"
serde               = "1.0"
serde_derive        = "1.0"
toml                = "0.5"
tobj                = "0.1"
walkdir             = "2"

